import { GoogleGenAI, Modality } from "@google/genai";

// Helper function to convert a File object to a base64 string
const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      // result is a data URL (e.g., "data:image/png;base64,iVBORw0KGgo...")
      // We only need the base64 part
      const result = reader.result as string;
      resolve(result.split(',')[1]);
    };
    reader.onerror = (error) => reject(error);
  });
};

export const removeBackground = async (imageFile: File, ai: GoogleGenAI): Promise<string> => {
  try {
    const base64Data = await fileToBase64(imageFile);

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Data,
              mimeType: imageFile.type,
            },
          },
          {
            text: 'Remove the background of this image, leaving only the main subject. The background should be transparent.',
          },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });
    
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageBytes: string = part.inlineData.data;
        // Return as a data URL that can be used directly in an <img> src
        return `data:image/png;base64,${base64ImageBytes}`;
      }
    }

    throw new Error('No image was generated by the API.');

  } catch (error) {
    console.error('Error removing background:', error);
    throw new Error('Failed to remove background from character image. Please try a different image or check your API key.');
  }
};
